FROM debian:jessie
MAINTAINER Major Hayden <major.hayden@rackspace.com>

ENV DEBIAN_FRONTEND noninteractive
RUN apt-get update
RUN apt-get -y install debootstrap

RUN mkdir /tmp/bootstrap

CMD ["/usr/sbin/debootstrap", "--variant=minbase", "--arch=amd64", "--include=python", "jessie", "/tmp/bootstrap", "http://mirror.rackspace.com/debian/"]
