FROM debian:jessie
MAINTAINER Major Hayden <major.hayden@rackspace.com>

# Set a temporary HTTP proxy on goomba to make updates faster
ENV http_proxy http://goomba.ohthree.com:3128

ENV DEBIAN_FRONTEND noninteractive
ADD sources.list /etc/apt/sources.list
RUN apt-get update
RUN apt-get -y install python locales debootstrap
RUN echo "en_US.UTF-8 UTF-8" > /etc/locale.gen && locale-gen

RUN mkdir /tmp/bootstrap

CMD ["/usr/sbin/debootstrap", "--variant=minbase", "--arch=amd64", "--include=python", "jessie", "/tmp/bootstrap", "http://mirrors.kernel.org/debian/"]
